# Generated by Django 4.2 on 2025-06-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='groq_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='preferred_model',
            field=models.CharField(default='llama-3.3-70b-versatile', max_length=100),
        ),
    ]
