# Generated by Django 5.2.1 on 2025-06-11 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_ai', '0002_book_groq_api_key_book_preferred_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='book_ai.book')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100)),
                ('feedback_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='book_ai.book')),
                ('rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='book_ai.responserating')),
            ],
        ),
    ]
